image:
  pullPolicy: IfNotPresent
  repository: docker.io
  image: redislabs/redisinsight
  tag: 1.13.1

volumes:
  host:
    /db:
      name: db
      path: /project/data/minikube/redisinsight
      type: DirectoryOrCreate

deployment:
  replicaCount: 1
  updateStrategy:
    type: Recreate

  containerSecurityContext:
    runAsUser: 0

  resources:
    requests:
      cpu: "100m"
      memory: "100Mi"

  env:
    RIPROXYENABLE: "True"
    RIAUTHPROMPT: "False"
    RITRUSTEDORIGINS: "https://zimagi-redis.${domain}"

  port: 8001

  livenessProbe:
    endpoint: "/healthcheck"

  readinessProbe:
    endpoint: "/healthcheck"

ingress:
  className: nginx
  tls:
    - secretName: origin-cert

services:
  redisinsight:
    autoscaling:
      enabled: false

    service:
      enabled: true
    ingress:
      enabled: true
      hosts:
        - host: "zimagi-redis.${domain}"
