image:
  pullPolicy: IfNotPresent
  repository: docker.io
  image: dbeaver/cloudbeaver
  tag: 23.0.0

volumes:
  host:
    /opt/cloudbeaver/workspace:
      name: workspace
      path: /project/data/minikube/cloudbeaver
      type: DirectoryOrCreate

deployment:
  replicaCount: 1
  updateStrategy:
    type: Recreate

  resources:
    requests:
      cpu: "100m"
      memory: "100Mi"

  port: 8978

ingress:
  className: nginx
  tls:
    - secretName: origin-cert

services:
  cloudbeaver:
    autoscaling:
      enabled: false

    service:
      enabled: true
    ingress:
      enabled: true
      hosts:
        - host: "zimagi-db.${domain}"
