#
# This file contains default settings for the Vagrant development environment.
#
# If you need to override any of these configurations on your own platform then
# copy this file into a "config.yml" in the vagrant directory
# (directory of this file) and your overrides will take effect on the next
# vagrant up or reload.
#
hostname: "cenv"
box_name: "ubuntu/bionic64"
user: "vagrant"
cpus: 1
memory_size: 2048
copy_vimrc: false
copy_profile: false
copy_bash_aliases: false
copy_bashrc: false
api_port: 5123
db_port: 5432
time_zone: "EST"
