version: '3.7'

x-mcmi: &mcmi
    image: ${MCMI_DEFAULT_RUNTIME_IMAGE}
    restart: always
    environment:
      MCMI_API_HOST: api
      MCMI_API_PORT: 5123
      MCMI_POSTGRES_HOST: data
      MCMI_POSTGRES_PORT: 5432
      MCMI_REDIS_HOST: tasks
      MCMI_REDIS_PORT: 6379
    env_file: .env
    depends_on:
      - data
      - tasks

services:
  api:
    << : *mcmi
    entrypoint: mcmi-api
    ports:
      - "5123:5123"

  scheduler:
    << : *mcmi
    entrypoint: mcmi-scheduler

  worker:
    << : *mcmi
    entrypoint: mcmi-worker

  data:
    image: postgres:12
    command: postgres -c 'max_connections=100'
    restart: always
    environment:
      POSTGRES_USER: ${MCMI_POSTGRES_USER}
      POSTGRES_PASSWORD: ${MCMI_POSTGRES_PASSWORD}
      POSTGRES_DB: ${MCMI_POSTGRES_DB}
    volumes:
      - /var/local/data/postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"

  tasks:
    image: redis:5
    restart: always
    command: redis-server --requirepass ${MCMI_REDIS_PASSWORD}
    volumes:
      - /var/local/data/redis:/data
    ports:
      - "6379:6379"
