global:
  data:
    ZIMAGI_APP_NAME: zimagi

    ZIMAGI_GITHUB_ORG: "${github_org}"

    ZIMAGI_DB_MAX_CONNECTIONS: 100
    ZIMAGI_REDIS_TYPE: redis

    ZIMAGI_THREAD_COUNT: 5
    ZIMAGI_MUTEX_TTL_SECONDS: 432000
    ZIMAGI_ENCRYPT_DATA: true

    ZIMAGI_DEBUG: true
    ZIMAGI_LOG_LEVEL: warning
    ZIMAGI_RESTART_SERVICES: false
    ZIMAGI_QUEUE_COMMANDS: true

    ZIMAGI_DISABLE_MODULE_INIT: false
    ZIMAGI_DISABLE_MODULE_SYNC: true

    ZIMAGI_EMAIL_HOST: smtp.gmail.com
    ZIMAGI_EMAIL_PORT: 587
    ZIMAGI_EMAIL_USE_TLS: true
    ZIMAGI_EMAIL_SUBJECT_PREFIX: "[Zimagi]> "

    ZIMAGI_LIB_PVC: ""
    ZIMAGI_HOST_APP_DIR: "/project/app"
    ZIMAGI_HOST_LIB_DIR: "/project/lib"

command-api:
  data:
    ZIMAGI_AUTO_UPDATE: true
    ZIMAGI_SERVER_TIMEOUT: 0
    ZIMAGI_SERVER_WORKERS: 3
    ZIMAGI_DISABLE_HTTPS: true
    ZIMAGI_ENCRYPT_COMMAND_API: false

data-api:
  data:
    ZIMAGI_AUTO_UPDATE: true
    ZIMAGI_SERVER_WORKERS: 3
    ZIMAGI_DISABLE_HTTPS: true
    ZIMAGI_ENCRYPT_DATA_API: false
    ZIMAGI_DISABLE_PAGE_CACHE: false
    ZIMAGI_PAGE_CACHE_SECONDS: 86400
    ZIMAGI_REST_PAGE_COUNT: 50

scheduler:
  data:
    ZIMAGI_AUTO_UPDATE: true

controller:
  data:
    ZIMAGI_AUTO_UPDATE: true

worker:
  data:
    ZIMAGI_AUTO_UPDATE: false
    ZIMAGI_WORKER_MAX_PROCESSES: 1

flower:
  data: {}
